# Generated by Django 5.2.1 on 2025-05-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('datum', models.DateField()),
                ('uhrzeit', models.TimeField()),
                ('dauer_minuten', models.IntegerField(default=60)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
