# Generated by Django 5.2.1 on 2025-05-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='termin',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='termin',
            name='patient_telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='termin',
            name='status',
            field=models.CharField(choices=[('frei', 'Frei'), ('gebucht', 'Gebucht')], default='frei', max_length=10),
        ),
        migrations.AlterField(
            model_name='termin',
            name='dauer_minuten',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterUniqueTogether(
            name='termin',
            unique_together={('datum', 'uhrzeit')},
        ),
    ]
